Update WebpackCleanupPlugin.js
Do not start plugin if the output folder is not exists.
First production build is fail because output folder not exist on server.

Error: ENOENT: no such file or directory, scandir '/Users/user/projects/project/public/assets/webpack'
    at Object.readdirSync (fs.js:981:3)
    at recursiveReaddirSync (/Users/user/projects/project/client/node_modules/recursive-readdir-sync/index.js:7:18)
    at getFiles (/Users/user/projects/project/client/node_modules/webpack-cleanup-plugin/lib/getFiles.js:25:50)
    at /Users/user/projects/project/client/node_modules/webpack-cleanup-plugin/lib/WebpackCleanupPlugin.js:46:44
....